
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/products
      username: rishav
      password: rishav
      driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: rishav
    password: rishav
    locations: classpath:db/migration

server:
  port: 8050
