spring:
  config:
    import: optional:configserver:http://localhost:8888 # This points to your Config Server's URL
  application:
    name: discovery-service # This is the service name registered in Eureka

server:
  port: 8761 # Port on which Eureka server runs

eureka:
  client:
    register-with-eureka: false # Eureka Server doesn't need to register with itself
    fetch-registry: false # Eureka Server doesn't need to fetch the registry from another server

  server:
    enable-self-preservation: false # Optional, disable for testing purposes
